# -*- mode: ruby -*-
# vi: set ft=ruby  :

bootstrap = <<SCRIPT
  useradd -m n0c
  cp -pr /home/vagrant/.ssh /home/n0c/
  chown -R n0c:n0c /home/n0c
  echo "n0c ALL=(ALL)       ALL" > /etc/sudoers.d/n0c
  sed -i 's/PasswordAuthentication/#PasswordAuthentication/' /etc/ssh/sshd_config
  sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux
  systemctl restart sshd
  systemctl disable firewalld
  echo "senhaTeste" | passwd --stdin n0c
  ip route add 0.0.0.0/25 via 10.10.87.1 dev eth1
  echo 8.8.8.8 > /etc/resolv.conf
  echo 1.1.1.1 >> /etc/resolv.conf
  echo "0.0.0.0/25 via 10.10.87.1 dev eth1" > /etc/sysconfig/route-eth1
SCRIPT


machines = {
  "Docker" => {
      "memory" => "2048", 
      "cpu" => "2", 
      "vlan" => "v-192", 
      "vlanGerencia" => "v-gerencia-servidores", 
      "ip" => "10.10.87.10", 
      "image" => "centos/7"}
}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}"
      machine.vm.network "private_network", ip: conf["ip"], netmask: "255.255.255.0" 
      machine.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)
    machine.vm.provision "shell", inline: "#{bootstrap}", privileged: true
    machine.vm.provider "vmware_esxi" do |vb|
      vb.esxi_hostname = 'ares.empresa.com.br'
    vb.esxi_username = 'n0c'
    vb.esxi_password = 'senhaUsuario'
    vb.guest_memsize = conf["memory"]
        vb.guest_numvcpus = conf["cpu"]
    vb.esxi_virtual_network = [conf["vlan"], conf["vlanGerencia"] ]
    vb.esxi_disk_store = 'Local'
    vb.guest_storage = '16'
    vb.guest_guestos = 'linux'
    vb.guest_name = "#{name}"
      end
    end
  end
end

